apiVersion: v1
kind: Service
metadata:
  name: tt-metrics-exporter
  labels:
    app.kubernetes.io/name: tt-metrics-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: tt-metrics-exporter
  ports:
    - name: metrics
      port: 9400
      targetPort: metrics
      protocol: TCP
