apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch.yaml
images:
  - name: tt-metrics-exporter
    newName: tt-metrics-exporter
    newTag: ttsim
